# SHARED PROPERTIES
direction: right
classes: {
  package: {
    shape: rectangle
    label.near: top-left
    style.font-size: 32
    style.bold: true
  }
  dependency: {
    style.stroke-dash: 3
    target-arrowhead: {
      shape: arrow
    }
  }
  implementation: {
    style.stroke-dash: 3
    target-arrowhead: {
      shape: triangle
      style.filled: false
    }
  }
  composition: {
    target-arrowhead: {
      shape: diamond
      style.filled: true
    }
  }
  aggregation: {
    target-arrowhead: {
      shape: diamond
      style.filled: false
    }
  }
  enum: {
    style.fill: "#0047AB"
    shape: class
  }
  abstract: {
    style.fill: "#C04000"
    shape: class
  }
  "class": {
    shape: class
  }
}

# Objects
# larger font
main: {
  class: package
  Context: {
    class: class
  }
}
ui: {
  class: package
  PcapUi: {
    class: class
  }
  FigureConfig: {
    class: class
  }
}
analyzer: {
  class: package
  BaseAnalyzer: {
    class: class
  }
  DNSAnalyzer: {
    class: class
  }
  DHCPAnalyzer: {
    class: class
  }
}
packet_parser: {
  class: package
  PcapParser: {
    class: class
  }
  DNSParser: {
    class: class
  }
  DHCPParser: {
    class: class
  }
  PcapParser -> DNSParser: {
    class: dependency
  }
  PcapParser -> DHCPParser: {
    class: dependency
  }
}
components: {
  class: package
  Layer: {
    class: class
  }
  Packet: {
    class: class
  }
  Layer -> Packet: {
    class: composition
  }
}
\layers': {
  LayerLevel -> LayerConfig: {
    class: composition
  }
  class: package
  LayerLevel: {
    class: enum
  }
  LayerConfig: {
    class: abstract
  }
  Ethernet: {
    class: class
  }
  ARP: {
    class: class
  }
  IP: {
    class: class
  }
  \.\.\.: {
    class: class
  }
  Ethernet -> LayerConfig: {
    class: implementation
  }
  ARP -> LayerConfig: {
    class: implementation
  }
  IP -> LayerConfig: {
    class: implementation
  }
  \.\.\. -> LayerConfig: {
    class: implementation
  }
}

main -> ui: {
  class: dependency
}
main -> packet_parser: {
  class: dependency
}
main -> analyzer: {
  class: dependency
}

# Inter-container links
packet_parser -> components: {
  class: dependency
}
analyzer -> components: {
  class: dependency
}
\layers'.LayerConfig -> components.Layer: {
  class: composition
}

# Explaining colors
Legend: {
  Abstract: {
    class: abstract
  }
  Enum: {
    class: enum
  }
  Class': {
    class: class
  }
  style.fill: "#FFFAF0"
}
